"""update

Revision ID: 30f062cba885
Revises: d204d19a5bc2
Create Date: 2021-06-15 20:39:15.392355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f062cba885'
down_revision = 'd204d19a5bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author', 'book', ['book_id'], ['id'])
    op.drop_constraint('book_author_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_author_id_fkey', 'book', 'author', ['author_id'], ['id'])
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###
