"""update

Revision ID: 6f642978a86a
Revises: e18f06688960
Create Date: 2021-06-15 20:48:41.927562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f642978a86a'
down_revision = 'e18f06688960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', sa.String(), nullable=True))
    op.drop_column('author', 'book_isd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_isd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###
