"""added book_id attribute

Revision ID: 9f99d1ededb1
Revises: b4a7117d8a9e
Create Date: 2021-06-15 20:32:03.503371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f99d1ededb1'
down_revision = 'b4a7117d8a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'book', ['book_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_column('book', 'book_id')
    # ### end Alembic commands ###
