"""update

Revision ID: b1242cccaddd
Revises: ba55307dc86f
Create Date: 2021-06-15 20:47:19.699696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1242cccaddd'
down_revision = 'ba55307dc86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_isd', sa.String(), nullable=True))
    op.drop_constraint('author_book_id_fkey', 'author', type_='foreignkey')
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('author_book_id_fkey', 'author', 'book', ['book_id'], ['id'])
    op.drop_column('author', 'book_isd')
    # ### end Alembic commands ###
