"""update

Revision ID: e18f06688960
Revises: b1242cccaddd
Create Date: 2021-06-15 20:47:36.754446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18f06688960'
down_revision = 'b1242cccaddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'author', 'book', ['book_id'], ['id'])
    op.drop_column('author', 'book_isd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_isd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###
